import { supabase } from './supabase'

function requireSupabase(){if(!supabase)throw new Error('Supabase belum dikonfigurasi.');return supabase}
export function slugify(value){return value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
export async function uploadCmsImage(file,folder){const client=requireSupabase();const extension=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${folder}/${Date.now()}-${crypto.randomUUID()}.${extension}`;const {error}=await client.storage.from('cms-media').upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;return path}
export async function removeCmsImage(path){if(!path)return;const client=requireSupabase();const {error}=await client.storage.from('cms-media').remove([path]);if(error)throw error}
export async function listAdminRows(table){const client=requireSupabase();const {data,error}=await client.from(table).select('*').order('created_at',{ascending:false});if(error)throw error;return data??[]}
export async function createBlog({judul,desc,imageFile,published}){const client=requireSupabase();let imagePath=null;try{if(imageFile)imagePath=await uploadCmsImage(imageFile,'articles');const {error}=await client.from('blogs').insert({judul,slug:slugify(judul),desc,image_path:imagePath,published});if(error)throw error}catch(error){if(imagePath)await removeCmsImage(imagePath).catch(()=>{});throw error}}
export async function updateBlog(id,current,{judul,desc,imageFile,published}){const client=requireSupabase();let nextImagePath=current.image_path,uploadedPath=null;if(imageFile){uploadedPath=await uploadCmsImage(imageFile,'articles');nextImagePath=uploadedPath}const {error}=await client.from('blogs').update({judul,slug:slugify(judul),desc,image_path:nextImagePath,published}).eq('id',id);if(error){if(uploadedPath)await removeCmsImage(uploadedPath).catch(()=>{});throw error}if(uploadedPath&&current.image_path)await removeCmsImage(current.image_path).catch(()=>{})}
export async function deleteBlog(row){const client=requireSupabase();const {error}=await client.from('blogs').delete().eq('id',row.id);if(error)throw error;if(row.image_path)await removeCmsImage(row.image_path).catch(()=>{})}
export async function createPhoto({judul,imageFile,published}){const client=requireSupabase();const imagePath=await uploadCmsImage(imageFile,'photos');const {error}=await client.from('photos').insert({judul,image_path:imagePath,published});if(error){await removeCmsImage(imagePath).catch(()=>{});throw error}}
export async function updatePhoto(id,current,{judul,imageFile,published}){const client=requireSupabase();let nextImagePath=current.image_path,uploadedPath=null;if(imageFile){uploadedPath=await uploadCmsImage(imageFile,'photos');nextImagePath=uploadedPath}const {error}=await client.from('photos').update({judul,image_path:nextImagePath,published}).eq('id',id);if(error){if(uploadedPath)await removeCmsImage(uploadedPath).catch(()=>{});throw error}if(uploadedPath&&current.image_path)await removeCmsImage(current.image_path).catch(()=>{})}
export async function deletePhoto(row){const client=requireSupabase();const {error}=await client.from('photos').delete().eq('id',row.id);if(error)throw error;if(row.image_path)await removeCmsImage(row.image_path).catch(()=>{})}
export async function createVideo({judul,youtube_code,published}){const client=requireSupabase();const {error}=await client.from('videos').insert({judul,youtube_code,published});if(error)throw error}
export async function updateVideo(id,{judul,youtube_code,published}){const client=requireSupabase();const {error}=await client.from('videos').update({judul,youtube_code,published}).eq('id',id);if(error)throw error}
export async function deleteVideo(row){const client=requireSupabase();const {error}=await client.from('videos').delete().eq('id',row.id);if(error)throw error}
