import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import ArticleCard from '../components/ArticleCard'
import { fallbackPhotos, programs, contact } from '../data/content'
import { getPublishedBlogs, getPublishedPhotos, getPublishedVideos } from '../lib/contentApi'
import { isSupabaseConfigured } from '../lib/supabase'

const fallbackVideos=[{id:'fallback-video',title:'Video Kegiatan PonPes',youtubeCode:'RE60uNdUFps'}]
export default function HomePage(){const [articles,setArticles]=useState([]),[photos,setPhotos]=useState(fallbackPhotos),[videos,setVideos]=useState(fallbackVideos);const joinUrl=`https://wa.me/${contact.whatsapp}?text=${encodeURIComponent('Assalamualaikum Ustad, Saya Ingin Belajar Di Pesantren Nurul Huda')}`;useEffect(()=>{if(!isSupabaseConfigured)return;Promise.all([getPublishedBlogs({limit:3}),getPublishedPhotos({limit:4}),getPublishedVideos({limit:3})]).then(([a,p,v])=>{setArticles(a);if(p.length)setPhotos(p);if(v.length)setVideos(v)}).catch(error=>console.error('CMS load error:',error))},[]);return <main>
<section id="hero" className="px-0"><div className="container text-center text-white"><div className="hero-title"><div className="hero-text">Selamat Datang <br/> Di PonPes Nurul Huda</div><p className="hero-p">Menggapai Ridlo Ilahi Robby dengan Ta&apos;lim wa Ta&apos;allum</p></div></div></section>
<section id="program" className="program-overlap"><div className="container"><div className="row g-3">{programs.map(program=><div className="col-lg-3 col-md-6" key={program.key}><div className="bg-white rounded-3 shadow p-3 d-flex justify-content-between align-items-center program-box"><div><h5>{program.title}</h5></div><img src={program.icon} height="55" width="55" alt=""/></div></div>)}</div></div></section>
<section id="berita" className="py-5 berita-home"><div className="container"><div className="header-berita text-center"><h2 className="fw-bold">Berita Kegiatan PonPes</h2></div><div className="row py-5 g-4">{articles.length?articles.map(item=><div className="col-lg-4" key={item.slug}><ArticleCard article={item}/></div>):<div className="col-12"><div className="alert alert-light border text-center py-4">Belum ada artikel yang dipublikasikan.</div></div>}</div><div className="footer-berita text-center"><Link to="/berita" className="btn btn-outline-success">Berita Lainnya</Link></div></div></section>
<section id="join" className="py-5"><div className="container py-5"><div className="row d-flex align-items-center"><div className="col-lg-6"><div className="d-flex align-items-center mb-3"><div className="stripe me-2"/><h5>Daftar Santri</h5></div><h1 className="fw-bold mb-2">Gabung Bersama Kami, Wujudkan Generasi Rabbani</h1><p className="mb-3">Kurikulum Pondok Pesantren Darunnajah adalah perpaduan kurikulum Pondok Modern Darussalam Gontor, Kurikulum Nasional dan Pesantren Salaf. Pelajaran-pelajaran Bahasa Arab dan Bahasa Inggris diajarkan langsung dengan bahasa aslinya. Pelajaran-pelajaran agama diajarkan dengan Bahasa Arab agar santri mendapatkan pemahaman yang seutuhnya. Pelajaran umum dan eksak diajarkan dalam bahasa Indonesia.</p><a href={joinUrl} target="_blank" rel="noreferrer" className="btn btn-outline-success">Daftar</a></div><div className="col-lg-6"><img src="/images/il-join-1.png" className="img-fluid" alt=""/></div></div></div></section>
<section id="video" className="py-5"><div className="container py-5"><div className="text-center"><iframe className="featured-video" src="https://www.youtube.com/embed/RE60uNdUFps?si=xBRKiw1HXJRkiftU" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div></div></section>
<section id="video_youtube" className="py-5"><div className="container py-5"><div className="header-berita text-center"><h2 className="fw-bold">Video Kegiatan PonPes</h2></div><div className="row py-5 g-3">{videos.map(item=><div className="col-lg-4" key={item.id}><iframe width="100%" height="215" src={`https://www.youtube.com/embed/${item.youtubeCode}`} title={item.title} allowFullScreen/></div>)}</div><div className="footer-berita text-center"><a href={contact.youtube} target="_blank" rel="noreferrer" className="btn btn-outline-success">Video Lainnya</a></div></div></section>
<section id="foto" className="section-foto parallax foto-home"><div className="container"><div className="d-flex justify-content-between align-items-center mb-5"><div className="d-flex align-items-center"><div className="stripe-putih me-2"/><h5 className="fw-bold text-white">Foto Kegiatan</h5></div><div><Link to="/foto" className="btn btn-outline-light">Foto Lainnya</Link></div></div><div className="row g-3">{photos.slice(0,4).map(photo=><div className="col-lg-3 col-md-6 col-6" key={photo.id}><a className="image-link" href={photo.image} target="_blank" rel="noreferrer"><img src={photo.image} className="img-fluid gallery-thumb" alt={photo.title}/></a><p>{photo.title}</p></div>)}</div></div></section>
</main>}
